version: 2
jobs:

  deploy_to_staging:
    docker:
      - image: google/cloud-sdk
    environment:
      - PROJECT_NAME: "my-app"
      - GOOGLE_PROJECT_ID: unified-chess-331509
      - GOOGLE_COMPUTE_ZONE: "us-central1-c"
      - GOOGLE_CLUSTER_NAME: "cluster-1"
    steps:
      - checkout
      - run: 
          name: Setup Google Cloud SDK
          command: |
            # apt-get install -qq -y gettext
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud projects list
            gcloud --project=test iam service-accounts list --format=json.
            # gcloud --quiet config set project unified-chess-331509
            # gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project unified-chess-331509
            # gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            # gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            # gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            whoami
      
   


workflows:
  version: 2
  build_test_deploy:
    jobs:
      
      - deploy_to_staging
          
          

            # envsubst < ${HOME}/project/ambassador.sh > ${HOME}/ambassador.sh
            # chmod +x ambassador.sh
            # bash ambassador.sh

            # envsubst < ${HOME}/project/cert-manager.sh > ${HOME}/cert-manager.sh
            # chmod +x cert-manager.sh
            # bash cert-manager.sh

            # envsubst < ${HOME}/project/external-dns.sh > ${HOME}/external-dns.sh
            # chmod +x external-dns.sh
            # bash external-dns.sh

            # envsubst < ${HOME}/project/reloader.sh > ${HOME}/reloader.sh
            # chmod +x reloader.sh
            # bash reloader.sh